import type { BlockTypeId, BlockProfile } from "./types";

/**
 * Catalogue of draggable infrastructure blocks.
 * Profiles are used by the validation + simulation engines.
 * Numbers are order-of-magnitude defaults for teaching, not SLAs.
 */
export const BLOCK_CATALOG: Record<BlockTypeId, BlockProfile> = {
  client: {
    label: "Client",
    category: "client",
    color: "#9ca3af",
    capacityRps: 0,
    latencyMs: 0,
    stateful: false,
    singleInstanceSpof: false,
    defaultReplicas: 1,
  },
  cdn: {
    label: "CDN",
    category: "edge",
    color: "#38bdf8",
    capacityRps: 200_000,
    latencyMs: 5,
    stateful: false,
    singleInstanceSpof: false,
    defaultReplicas: 1,
  },
  loadBalancer: {
    label: "Load Balancer",
    category: "edge",
    color: "#22d3ee",
    capacityRps: 100_000,
    latencyMs: 2,
    stateful: false,
    singleInstanceSpof: true,
    defaultReplicas: 2,
  },
  apiGateway: {
    label: "API Gateway",
    category: "edge",
    color: "#a78bfa",
    capacityRps: 50_000,
    latencyMs: 8,
    stateful: false,
    singleInstanceSpof: true,
    defaultReplicas: 2,
  },
  waf: {
    label: "WAF / Firewall",
    category: "security",
    color: "#f472b6",
    capacityRps: 80_000,
    latencyMs: 3,
    stateful: false,
    singleInstanceSpof: true,
    defaultReplicas: 2,
  },
  rateLimiter: {
    label: "Rate Limiter",
    category: "security",
    color: "#fb7185",
    capacityRps: 60_000,
    latencyMs: 1,
    stateful: true,
    singleInstanceSpof: true,
    defaultReplicas: 2,
  },
  authService: {
    label: "Auth Service",
    category: "security",
    color: "#c084fc",
    capacityRps: 20_000,
    latencyMs: 15,
    stateful: true,
    singleInstanceSpof: true,
    defaultReplicas: 2,
  },
  webService: {
    label: "Web/App Service",
    category: "compute",
    color: "#d4ff40",
    capacityRps: 5_000,
    latencyMs: 25,
    stateful: false,
    singleInstanceSpof: true,
    defaultReplicas: 3,
  },
  function: {
    label: "Serverless Function",
    category: "compute",
    color: "#facc15",
    capacityRps: 10_000,
    latencyMs: 40,
    stateful: false,
    singleInstanceSpof: false,
    defaultReplicas: 1,
  },
  cache: {
    label: "Cache (Redis)",
    category: "data",
    color: "#ef4444",
    capacityRps: 100_000,
    latencyMs: 1,
    stateful: true,
    singleInstanceSpof: true,
    defaultReplicas: 2,
  },
  relationalDb: {
    label: "Relational DB",
    category: "data",
    color: "#3b82f6",
    capacityRps: 8_000,
    latencyMs: 10,
    stateful: true,
    singleInstanceSpof: true,
    defaultReplicas: 2,
  },
  nosqlDb: {
    label: "NoSQL DB",
    category: "data",
    color: "#10b981",
    capacityRps: 30_000,
    latencyMs: 6,
    stateful: true,
    singleInstanceSpof: true,
    defaultReplicas: 3,
  },
  messageQueue: {
    label: "Message Queue",
    category: "async",
    color: "#f59e0b",
    capacityRps: 40_000,
    latencyMs: 4,
    stateful: true,
    singleInstanceSpof: true,
    defaultReplicas: 3,
  },
  objectStorage: {
    label: "Object Storage (S3)",
    category: "data",
    color: "#14b8a6",
    capacityRps: 25_000,
    latencyMs: 20,
    stateful: true,
    singleInstanceSpof: false,
    defaultReplicas: 1,
  },
  search: {
    label: "Search (ES)",
    category: "data",
    color: "#6366f1",
    capacityRps: 15_000,
    latencyMs: 18,
    stateful: true,
    singleInstanceSpof: true,
    defaultReplicas: 3,
  },
  streamProc: {
    label: "Stream Processor",
    category: "async",
    color: "#eab308",
    capacityRps: 35_000,
    latencyMs: 12,
    stateful: true,
    singleInstanceSpof: false,
    defaultReplicas: 3,
  },
  analytics: {
    label: "Analytics / Warehouse",
    category: "data",
    color: "#8b5cf6",
    capacityRps: 5_000,
    latencyMs: 50,
    stateful: true,
    singleInstanceSpof: false,
    defaultReplicas: 1,
  },
};

export const BLOCK_ORDER: BlockTypeId[] = [
  "client",
  "cdn",
  "loadBalancer",
  "apiGateway",
  "waf",
  "rateLimiter",
  "authService",
  "webService",
  "function",
  "cache",
  "relationalDb",
  "nosqlDb",
  "messageQueue",
  "objectStorage",
  "search",
  "streamProc",
  "analytics",
];

export function getBlockProfile(type: BlockTypeId): BlockProfile {
  return BLOCK_CATALOG[type];
}
