/**
 * SKILL.md exporter for a system-design canvas.
 *
 * Generates a markdown "skill" document describing the architecture:
 * inventory of components, data flow edges, and current validation notes.
 * The idea: paste it into an AI agent's skill dir so the agent understands
 * the design when working with the repo.
 */

import type { CanvasDocument } from "@/lib/types";
import { BLOCK_CATALOG } from "@/lib/catalog";
import { validateDesign } from "@/lib/engine/validation";

function replicasOf(config?: Record<string, unknown>, fallback = 1): number {
  const r = config?.replicas;
  if (typeof r === "number" && Number.isFinite(r) && r > 0) return r;
  return fallback;
}

export function toSkillMd(doc: CanvasDocument): string {
  const name = doc.meta.name || "Untitled design";
  const byId = new Map(doc.nodes.map((n) => [n.id, n]));
  const validation = validateDesign(doc);

  const out: string[] = [];
  out.push(`# ${name}`);
  out.push("");
  if (doc.meta.description) {
    out.push(`> ${doc.meta.description}`);
    out.push("");
  }
  out.push("System design whiteboard — generated by Tony System Design.");
  out.push("");

  out.push("## Components");
  out.push("");
  if (doc.nodes.length === 0) {
    out.push("_(no components yet)_");
  } else {
    out.push("| Component | Type | Replicas | Capacity (req/s) | Latency (ms) |");
    out.push("|---|---|---|---|---|");
    for (const n of doc.nodes) {
      const p = BLOCK_CATALOG[n.type];
      const r = replicasOf(n.config, p.defaultReplicas);
      out.push(
        `| ${n.label} | ${p.label} | ${r} | ${p.capacityRps} | ${p.latencyMs} |`,
      );
    }
  }
  out.push("");

  out.push("## Data flow");
  out.push("");
  if (doc.edges.length === 0) {
    out.push("_(no connections yet)_");
  } else {
    for (const e of doc.edges) {
      const s = byId.get(e.source);
      const t = byId.get(e.target);
      if (!s || !t) continue;
      out.push(`- ${s.label} → ${t.label}`);
    }
  }
  out.push("");

  out.push("## Validation notes");
  out.push("");
  if (validation.findings.length === 0) {
    out.push("No issues found.");
  } else {
    for (const f of validation.findings) {
      const icon =
        f.severity === "error" ? "❌" : f.severity === "warn" ? "⚠️" : "ℹ️";
      out.push(`- ${icon} **${f.severity}**: ${f.message}`);
      if (f.hint) out.push(`  - Hint: ${f.hint}`);
    }
  }
  out.push("");

  return out.join("\n");
}
